name: excercise_2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_svg: ^2.0.0+1
  intl: ^0.18.0
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  build_runner: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    #images 
    - assets/image/
    - assets/vector/
    - assets/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans/OpenSans-Light.ttf
          style: normal
          weight: 300
        - asset: assets/font/OpenSans/OpenSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/font/OpenSans/OpenSans-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/font/OpenSans/OpenSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/font/OpenSans/OpenSans-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/font/OpenSans/OpenSans-ExtraBold.ttf
          style: normal
          weight: 900


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
